#!/usr/bin/env python
import sys, os

from util.log import setup_logging

USAGE = "Usage: ./run <web|sched|once|queue|js>"

def main():
    setup_logging()

    if not len(sys.argv) > 1:
        print USAGE
        sys.exit(1)

    if sys.argv[1] == "web":
        from emporium import app, setup, get_js_templates

        port = 5000
        if len(sys.argv) > 2 and sys.argv[2] == "test":
            print "Enabling test mode..."
            app.config["TESTING"] = True
            port = 8321

        setup()
        app.run("0.0.0.0", port=port, debug=True, extra_files=list(get_js_templates()))
        sys.exit(0)

    if sys.argv[1] == "queue":
        from queue.queue import start_queues
        start_queues()

    if sys.argv[1] == "sched":
        from scheduler.run import sched
        sched.run()
        sys.exit(0)

    if sys.argv[1] == "js":
        from emporium import build_js_templates
        build_js_templates()
        sys.exit(0)

    if sys.argv[1] == "once":
        import scheduler.run

        if len(sys.argv) < 3:
            print "Usage: ./run.py once <task>"
            sys.exit(1)

        if sys.argv[2] in dir(scheduler.run):
            getattr(globals()["scheduler"].run, sys.argv[2])()
        sys.exit(0)

    print USAGE
    sys.exit(1)

if __name__ == "__main__":
    main()

